const ERROR_CODE_VALIDATION = 400;
const ERROR_CODE_NOT_FOUND = 404;
const ERROR_CODE_DEFAULT = 500;
const ERROR_CODE_AUTHORIZATION = 401;
const ERROR_CODE_FORBIDDEN = 403;
const ERROR_CODE_CONFLICTING_REQUEST = 409;

module.exports = {
  ERROR_CODE_NOT_FOUND,
  ERROR_CODE_VALIDATION,
  ERROR_CODE_DEFAULT,
  ERROR_CODE_AUTHORIZATION,
  ERROR_CODE_FORBIDDEN,
  ERROR_CODE_CONFLICTING_REQUEST,
};
